version: "3"
services:
  work:
    build:
      context: .
      dockerfile: ./work/Dockerfile
    command: ["bash"]
    stdin_open: true
  app:
    build:
      context: .
      dockerfile: ./dotnet/Dockerfile
    stdin_open: true
    depends_on:
      - "db"
    volumes:
      - ./src:/app
    ports:
      - 5000:5000
    command: ["dotnet", "watch", "run"]
    environment: 
      # DOTNET_USE_POLLING_FILE_WATCHER: 1
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "server=db;userid=${DB_USER};password=${DB_PASS};database=${DB_NAME};Charset='utf8';"
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 13307:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./mysql/mysql.conf:/etc/mysql/conf.d/my.cnf
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
volumes:
  db-store: